
name: Laravel Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deployment
        run: ssh ubuntu@54.81.51.120 "php artisan migrate"
